<a href="https://colab.research.google.com/github/kurek0010/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [3]:
import numpy as np
np.__version__

'1.25.2'

In [6]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

1D Array

In [9]:
x = np.array([1, 3])
x

array([1, 3])

In [10]:
print(x)

[1 3]


In [11]:
type(x)

numpy.ndarray

In [12]:
x.ndim

1

In [13]:
x.shape

(2,)

In [14]:
x.size

2

In [15]:
x.dtype

dtype('int64')

In [16]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [17]:
x.dtype

dtype('float64')

2D Array

In [18]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [19]:
x.ndim

2

In [20]:
x.shape

(2, 2)

In [4]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [21]:
x.shape

(2, 2)

3D Array

In [22]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [23]:
x.ndim

3

In [24]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [25]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [26]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [29]:
A = np.array([1, 2, 3], dtype='float')
A.dtype


dtype('float64')

In [30]:
A

array([1., 2., 3.])

In [31]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [33]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [34]:
A

array([1, 2, 3])

In [35]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [39]:
A = np.array([24, 120, 100], dtype=np.int8)
A.dtype

dtype('int8')

In [37]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [40]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [49]:
np.arange(start=10, stop=101, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [51]:
np.arange(start=100, stop=1, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [54]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [58]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [60]:
A + B

array([6, 0, 7, 4])

In [61]:
A - B

array([0, 2, 1, 0])

In [62]:
A * B

array([ 9, -1, 12,  4])

In [63]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [64]:
np.add(A, B)

array([6, 0, 7, 4])

In [65]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [68]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [69]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [71]:
A + 3

array([6, 4, 7, 5])

In [72]:
2 * A

array([6, 2, 8, 4])

In [73]:
A + 3*B

array([12, -2, 13,  8])

In [74]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [75]:
X * Y

array([[6, 0],
       [2, 0]])

In [76]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [78]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [79]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [80]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [83]:
np.random.seed(0)

In [82]:
np.random.randn()

1.764052345967664

In [84]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [85]:
np.random.randn(10, 4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [86]:
np.random.rand()

0.15896958364551972

In [87]:
np.random.rand(10)

array([0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
       0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947])

In [88]:
np.random.rand(10, 2)

array([[0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895]])

In [90]:
np.random.randint(10)

3

In [92]:
np.random.randint(low=10, high=101)

42

In [94]:
np.random.randint(low=10, high=101, size=10)

array([34, 12, 13, 23, 50, 82, 29, 82, 36, 76])

In [105]:
np.random.choice([4, 2, 1, 3, 5])

3

In [120]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [121]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.random.shuffle(data)

In [125]:
data

array([0, 2, 5, 9, 6, 1, 8, 3, 7, 4])

### <a name='a6'></a> Podstawowe funkcje

In [128]:
np.exp(2.4)

11.023176380641601

In [130]:
np.sqrt(25)

5.0

In [132]:
np.all([2, 3, 1])

True

In [134]:
np.any([0, 0, 0])

False

In [135]:
bool(1.3)

True

In [136]:
A = np.random.rand(5)
A

array([0.96896177, 0.32099724, 0.22126269, 0.1412639 , 0.09725993])

In [137]:
np.argmax(A)

0

In [138]:
A[np.argmax(A)]

0.9689617652602737

In [139]:
np.argmin(A)

4

In [141]:
np.argsort(A)

array([4, 3, 2, 1, 0])

In [142]:
np.max(A)

0.9689617652602737

In [143]:
np.min(A)

0.09725992706317388

In [144]:
np.mean(A)

0.3499491047613249

In [145]:
np.median(A)

0.22126268518378278

In [148]:
np.std(A)

0.3187401487078218

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [149]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [150]:
A[2]

2

In [151]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [152]:
A[:2]

array([0, 1])

In [153]:
A[[0, 2]]

array([0, 2])

In [155]:
A[-3]

17

In [157]:
A[10:15]

array([10, 11, 12, 13, 14])

In [161]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [163]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [165]:
A[1, 2] = 21
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 21,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [167]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 21,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [168]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 21  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [170]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 21]
[10 11 12]
[15 16 17]


In [171]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
21
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [172]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 21,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [173]:
A.shape

(4, 5)

In [174]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 21],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [175]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 21,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [176]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 21, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [177]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [178]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [179]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [180]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [181]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])